

logging.file: logs/application.log
logging:
  level:
      org:
        springframework:
          web: DEBUG
        hibernate: ERROR
server:
  port: 8888
spring:
  datasource:
    url: jdbc:h2:file:./db/court
    driver-class-name: org.h2.Driver
    username: sa
    password:
    database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
